name: Type Check

on:
  push:
    branches: [ develop, feat/type* ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '30 0 * * 0'

defaults:
  run:
    shell: bash -ieol pipefail {0}

jobs:
  type_check:
    name: Build
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    runs-on:
      - ubuntu-latest
    # runs-on:
    #   - self-hosted
    #   - macOS
    #   - mobile
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: '[Linux] Setup Nodejs and Yarn'
        if: runner.os == 'Linux'
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Run Type Check
        run: |
          # yarn config set npmRegistryServer https://registry.npmmirror.com
          cd apps/mobile;
          yarn install;
          time yarn typecheck;


